### ISSUE TITLE
[Question] About the armotize...

### ISSUE THREAD

**Issue by WayneY** [dallaslu/beancount-periodic#1]
Is that intentially cash basis or accural basis? 

For cash basis the rent expense is usually recorded only when the payment is issued, and if paid yearly, it will be only recorded once in a year.
For accural basis, it is usually recored as an asset in the prepaid expenses account if paid in advance, and then decreased in period into the expense.

But here the armotize is using the equtiy account... I do not understand the rule here and the purpose for...

**Comment by dallaslu** [comment]
It should be based on a loose accrual basis. In fact, in the original design, this plugin should provide options or additional meta to configure the transit account. But at present, we have to provide the default behavior you see based on the simple principle of 'amortize expenses, depreciate assets'.

The equity account is used to ensure that the asset reports before and after the plug-in is enabled remain unchanged. If you think this is a expense before using the plugin, your assets will be reduced when the expense occurs, and the plugin should not effect this.

But if you think it is still an asset after payment, the asset should be depreciated.

If both default behaviors do not meet your expectations, you can use `recur` to complete them.

So, you can choose one of the following 3 methods:

## 1. `amortize`

```beancount
2022-07-18 * "Landlord" "Rent Q3"
  Assets:Cash  -3000 USD
  Expenses:Home:Rent
    amortize: "3M /M"
```
Be equal to:

```beancount
2022-07-18 * "Landlord" "Rent Q3"
  Assets:Cash  -3000 USD
  Equity:Amortization:Home:Rent
2022-07-18 * "Landlord" "Rent Q3 Amortized(1/3)"
  Equity:Amortization:Home:Rent  -1000 USD
  Expenses:Home:Rent
2022-08-18 * "Landlord" "Rent Q3 Amortized(1/3)"
  Equity:Amortization:Home:Rent  -1000 USD
  Expenses:Home:Rent
2022-09-18 * "Landlord" "Rent Q3 Amortized(1/3)"
  Equity:Amortization:Home:Rent  -1000 USD
  Expenses:Home:Rent
```
## 2. `depreciate`
### Prepaid
```beancount
2022-07-18 * "Landlord" "Rent Q3"
  Assets:Cash  -3000 USD
  Assets:Prepaid:Home:Rent ; or just `Assets:Prepaid`
    depreciate: "3M /M"
```
Be equal to:

```beancount
2022-07-18 * "Landlord" "Rent Q3"
  Assets:Cash  -3000 USD
  Assets:Prepaid:Home:Rent ; or just `Assets:Prepaid`
2022-07-18 * "Landlord" "Rent Q3 Depreciated(1/3)"
  Assets:Prepaid:Home:Rent  -1000 USD
  Expenses:Depreciation:Prepaid:Home:Rent ; or `Expenses:Depreciation:Prepaid`
2022-08-18 * "Landlord" "Rent Q3 Depreciated(1/3)"
  Assets:Prepaid:Home:Rent  -1000 USD
  Expenses:Depreciation:Prepaid:Home:Rent
2022-09-18 * "Landlord" "Rent Q3 Depreciated(1/3)"
  Assets:Prepaid:Home:Rent  -1000 USD
  Expenses:Depreciation:Prepaid:Home:Rent
```
### Assets
```beancount
2022-07-18 * "Landlord" "Rent Q3"
  Assets:Cash  -3000 USD @@ 3 MONTH
  Assets:Home:Rent:Apartment 3 MONTH;
    depreciate: "3M /M"
```
Be equal to:
```beancount
2022-07-18 * "Landlord" "Rent Q3"
  Assets:Cash  -3000 USD @@ 3 MONTH
  Assets:Home:Rent:Apartment 3 MONTH;
2022-07-18 * "Landlord" "Rent Q3 Depreciated(1/3)"
  Assets:Prepaid:Home:Rent  -1 MONTH
  Expenses:Depreciation:Home:Rent:Apartment
2022-08-18 * "Landlord" "Rent Q3 Depreciated(1/3)"
  Assets:Prepaid:Home:Rent  -1 MONTH
  Expenses:Depreciation:Home:Rent:Apartment
2022-09-18 * "Landlord" "Rent Q3 Depreciated(1/3)"
  Assets:Prepaid:Home:Rent  -1 MONTH
  Expenses:Depreciation:Home:Rent:Apartment
```

## 3. `recur`
```beancount
2022-07-18 * "Rent Q3"
  Assets:Cash  -3000 USD
  Assets:Prepaid

2022-07-18 * "Landlord" "Rent Q3"
  recur: "3M /M"
  Assets:Prepaid -1000 USD
  Expense:Home:Rent
```
Be equal to:
```beancount
2022-07-18 *
  Assets:Cash  -3000 USD
  Assets:Prepaid;
2022-07-18 * "Landlord" "Rent Q3 Recurring(1/3)"
  Assets:Prepaid  -1000 USD
  Expenses:Home:Rent
2022-08-18 * "Landlord" "Rent Q3 Recurring(2/3"
  Assets:Prepaid  -1000 USD
  Expenses:Home:Rent
2022-09-18 * "Landlord" "Rent Q3 Recurring(3/3)"
  Assets:Prepaid  -1000 USD
  Expenses:Home:Rent
```
At this time, you can also use the `Equity` account ( or `Assets:Home:Rent:Apartment` ), which will not be repeated.

**Comment by WayneY** [comment]
Thanks, now it's clear to me.
