### ISSUE TITLE
How do you depreciate to 27.5 years?

### ISSUE THREAD

**Issue by lvh** [dallaslu/beancount-periodic#6]
By convention, most U.S. residential rental property is typically depreciated at a rate of 3.636% each year for 27.5 years. beancount-periodic seems to refuse to want to parse `27.5`.

```
2022-03-31 * "Building"
  Assets:Address:Building 300000 USD
  Equity:Owners
    depreciate: "27.5 Year /Yearly =80000"
```

**Comment by dallaslu** [comment]
The time configuration is expected to be a specific date, so decimals are not currently supported. For example, the date corresponding to 1.1 years is not clear enough for humans and programs.

Returning to the case, perhaps the most logical way to write it would be:

```beancount
2022-03-31 * "Building"
  Assets:Address:Building 300000 USD
  Equity:Owners
    depreciate: "27Y+6M /Yearly =80000"
```

But the current version doesn't support that either. 

Now, you can try alternative solution like this:

```beancount
2022-03-31 * "Building"
  Assets:Address:Building 300000 USD
  Equity:Owners
    depreciate: "330 Months /Yearly =80000" ;27.5 Years
```

**Comment by lvh** [comment]
Thanks! This worked perfectly :)
